# Generated by Django 4.2.13 on 2024-05-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('Abbottabad', 'Abbottabad'), ('Bahawalpur', 'Bahawalpur'), ('Bannu', 'Bannu'), ('Chiniot', 'Chiniot'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gujranwala', 'Gujranwala'), ('Gujrat', 'Gujrat'), ('Hyderabad', 'Hyderabad'), ('Islamabad', 'Islamabad'), ('Jhang', 'Jhang'), ('Jhelum', 'Jhelum'), ('Karachi', 'Karachi'), ('Kasur', 'Kasur'), ('Khushab', 'Khushab'), ('Lahore', 'Lahore'), ('Larkana', 'Larkana'), ('Mandi Bahauddin', 'Mandi Bahauddin'), ('Mardan', 'Mardan'), ('Multan', 'Multan'), ('Murree', 'Murree'), ('Muzaffarabad', 'Muzaffarabad'), ('Nawabshah', 'Nawabshah'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Rawalpindi', 'Rawalpindi'), ('Sahiwal', 'Sahiwal'), ('Sargodha', 'Sargodha'), ('Sheikhupura', 'Sheikhupura'), ('Sialkot', 'Sialkot'), ('Sukkur', 'Sukkur'), ('Swat', 'Swat'), ('Vehari', 'Vehari')], max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Azad Kashmir', 'Azad Kashmir'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=100)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orderplaced',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
